services:
  # A Docker web service
  - type: web
    name: feiertage-wrapper
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: uv sync --frozen
    startCommand: fastapi run app/main.py --host 0.0.0.0 --port 8000
